version: '3'

services:
  hadoop-master:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-master
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop-network
    ports:
      - '9870:9870' # Namenode UI
      - '8088:8088' # Resource Manager UI

  hadoop-slave1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-slave1
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - hadoop-network
    # Add port mappings if required by other services

volumes:
  hadoop_namenode:
  hadoop_datanode1:

networks:
  hadoop-network:
    driver: bridge
