version: "3.3"
services:
  spark-batch-master:
    build: .
    container_name: spark-batch-master
    networks:
      - network1
    ports:
      - "9090:8080"
      - "7077:7077"
      - "4040:4040"
      - "7003:7000"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-batch-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    build: .
    container_name: spark-worker-a
    networks:
      - network1
    ports:
      - "9091:8080"
      - "7002:7000"
    depends_on:
      - spark-batch-master
    environment:
      - SPARK_MASTER=spark://spark-batch-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  spark-worker-b:
    build: .
    container_name: spark-worker-b
    networks:
      - network1
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-batch-master
    environment:
      - SPARK_MASTER=spark://spark-batch-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data

networks:
  network1:
    name: mynetwork
    driver: bridge
