version: "3"

services:
  consumer:
    build: .
    container_name: consumer
    restart: "always"
    networks:
      - mynetwork
    volumes:
      - ${PWD}/app:/consumer/app

networks:
  mynetwork:
    external: true

volumes:
  app:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/app

